In [ ]:
#ICP 3 - Ryan Naugher

In [9]:
#Importing the numpy package for use in np.mean, np.array, np.arange, and np.reshape
import numpy as np

In [19]:
#Part 1
#Creating the Employee class
class Employee:
    numEmp = 0
    #Resetting the number of employees to zero
    salaries = []
    #Resetting/Creating list of employee salaries
    #Creating a constructor that includes name, family, salary, and department
    def __init__(self, name, family, salary, department):
        #Setting each of the constructors values equal to the user inputted values
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        #Adding 1 to the numEmp variable to keep track of the number of employees each time the constructor is called
        Employee.numEmp += 1
        #Appending the employees' salary to the salaries list to have salaries stored in one spot
        Employee.salaries.append(salary)
        #Function to find the average salary of all employees, the function takes self as a parameter which allows us to 
        #use anything within the Employee class
    def avg_salary(self):
        #Using numpy mean function to compute the average salary using the salaries list created earlier
        #return np.mean(self.salaries)
        #Using the summation of the salaries in the list divided by the total number of employees to get the average
        return sum(self.salaries)/self.numEmp
    #Creating a new class that inherits everything from the Employee class
class Fulltime_Employee(Employee):
    #Passes everything from Employee to Fulltime_Employee
    pass

In [20]:
#Adding employees using the constructor and entering all parameters
emp1 = Employee("Ryan", "Naugher", 50000, "CS")
emp2 = Employee("Test", "Name", 10000, "English")
emp3 = Employee("Name", "Test", 40000, "Math")
#Average Salary output
print(Employee.avg_salary(Employee))
#Number of employees output
print(Employee.numEmp)
#Repeated using Fulltime_Employee class
print(Fulltime_Employee.avg_salary(Fulltime_Employee))
print(Fulltime_Employee.numEmp)

33333.333333333336
3
33333.333333333336
3


In [21]:
#Part 2
#Creating an array of numbers 1-20 float values using the array and arange function and setting dtype to float
x = np.array(np.arange(1,21,dtype=float))
print(x)
print()
#Reshaping the created array to a 4x5 matrix using the reshape function
x = x.reshape(4,5)
print(x)
print()
#Using list comprehension to access the last entry of each row and setting them all to zero
x[:,[4]] = 0
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]

[[ 1.  2.  3.  4.  0.]
 [ 6.  7.  8.  9.  0.]
 [11. 12. 13. 14.  0.]
 [16. 17. 18. 19.  0.]]
